name: Request a change to a blog post
description: Typo, broken link, or inaccurate information in the Blog
title: 'Request change to [Blog]'
labels: typo
assignees:
  - dannyhines
body:
  - type: markdown
    attributes:
      value: |
        Typo, broken link, or inaccurate information? Thanks for letting me know!
  - type: textarea
    id: whats-wrong
    attributes:
      label: What do I need to fix?
      placeholder: The link to Jasper.ai doesn't work
    validations:
      required: true
